from pathlib import Path

from vector_lab.cluster.adapters import BonechoAdapter
from vector_lab.config.models import bonecho_defaults
from vector_lab.config.store import PROFILES_DIRNAME, ConfigStore
from vector_lab.images.state import ImageArtifactState, ImageStateStore
from vector_lab.jobs.generate import generate_runtime
from vector_lab.jobs.sync import GENERATED_REMOTE_SUBDIR, stage_generated_into_repo


def test_package_and_config_names() -> None:
    import vector_lab

    assert vector_lab.__version__ == "0.1.0"
    assert PROFILES_DIRNAME == ".vector-lab"


def test_generated_paths_use_vector_lab(tmp_path: Path) -> None:
    repo = tmp_path / "IsaacLab"
    repo.mkdir()
    profile = bonecho_defaults()
    profile.remote_user = "alice"
    profile.scratch_dir = "/scratch/alice"
    BonechoAdapter().derive_scratch_paths(profile)
    generated = generate_runtime(profile)
    dest = stage_generated_into_repo(repo, generated.as_dict())
    assert dest == repo / ".vector-lab" / "generated"
    assert GENERATED_REMOTE_SUBDIR == ".vector-lab/generated"
    blob = generated.env_cluster + generated.submit_job_slurm + generated.run_singularity
    assert ".isaac-cluster" not in blob
    assert "isaac-cluster" not in blob
    assert "issac-cluster" not in blob
    assert "Generated by vector-lab" in blob
    assert "CLUSTER_ISAACLAB_DIR=" in generated.env_cluster
    assert "DOCKER_ISAACLAB_PATH=" in generated.env_cluster
    assert "--writable-tmpfs" in generated.run_singularity
    assert "mollysun" not in blob
    assert "/home/" not in blob


def test_images_state_readable_after_local_migration(tmp_path: Path) -> None:
    old = tmp_path / ".isaac-cluster"
    (old / "state").mkdir(parents=True)
    (old / "artifacts").mkdir()
    store_old = ConfigStore(old)
    ImageStateStore(store_old).upsert(
        ImageArtifactState(
            image_profile="base",
            docker_image="isaac-lab-base:latest",
            built_image_digest="sha256:abc",
            local_artifact_sha256="deadbeef",
        )
    )
    new = tmp_path / ".vector-lab"
    old.rename(new)
    loaded = ImageStateStore(ConfigStore(new)).get("base")
    assert loaded is not None
    assert loaded.built_image_digest == "sha256:abc"
    assert loaded.local_artifact_sha256 == "deadbeef"
    assert ConfigStore.locate(start=tmp_path).root == new.resolve()
