"""Render inspectable cluster runtime wrappers from a profile.

Templates are generic. Vector SLURM behavior appears only when the profile/adapter
supplies login-shell SLURM, Apptainer module, and writable-tmpfs exec flags.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from vector_sim.cluster.slurm import gres_request, slurm_time
from vector_sim.compat import WRAPPER_SCHEMA_VERSION
from vector_sim.config.models import ClusterProfile
from vector_sim.errors import ConfigError

ENV_NAME = "env.cluster"
SUBMIT_NAME = "submit_job_slurm.sh"
RUNNER_NAME = "run_singularity.sh"
GUI_BOOTSTRAP_NAME = "gui_bootstrap.sh"

PERSISTENT_CACHE_BINDS = (
    ("cache/kit", "${DOCKER_ISAACSIM_ROOT_PATH}/kit/cache"),
    ("cache/ov", "${DOCKER_USER_HOME}/.cache/ov"),
    ("cache/pip", "${DOCKER_USER_HOME}/.cache/pip"),
    ("cache/glcache", "${DOCKER_USER_HOME}/.cache/nvidia/GLCache"),
    ("cache/computecache", "${DOCKER_USER_HOME}/.nv/ComputeCache"),
    ("logs", "${DOCKER_USER_HOME}/.nvidia-omniverse/logs"),
    ("data", "${DOCKER_USER_HOME}/.local/share/ov/data"),
    ("documents", "${DOCKER_USER_HOME}/Documents"),
)


@dataclass
class GeneratedRuntime:
    env_cluster: str
    submit_job_slurm: str
    run_singularity: str
    gui_bootstrap: str | None = None

    def as_dict(self) -> dict[str, str]:
        files = {
            ENV_NAME: self.env_cluster,
            SUBMIT_NAME: self.submit_job_slurm,
            RUNNER_NAME: self.run_singularity,
        }
        if self.gui_bootstrap is not None:
            files[GUI_BOOTSTRAP_NAME] = self.gui_bootstrap
        return files


def persistent_remote_dirs(profile: ClusterProfile) -> list[str]:
    dirs = [
        profile.paths.cache,
        profile.paths.workspace,
        profile.paths.logs,
        profile.paths.containers,
    ]
    return [d for d in dirs if d]


PLACEHOLDER_TOKENS = ("<user>", "<username>", "<remote_user>")


def assert_concrete_cluster_paths(profile: ClusterProfile) -> None:
    """Refuse generated configs that still contain username placeholders."""
    blobs = [
        profile.remote_user or "",
        profile.home_dir or "",
        profile.scratch_dir or "",
        profile.paths.cache or "",
        profile.paths.logs or "",
        profile.paths.containers or "",
        profile.paths.workspace or "",
    ]
    for value in blobs:
        lowered = value.lower()
        for token in PLACEHOLDER_TOKENS:
            if token in lowered:
                raise ConfigError(
                    f"cluster path still contains placeholder {token!r}: {value}",
                    suggestion="Run vector-sim setup so the real remote username is discovered.",
                )


def render_env_cluster(
    profile: ClusterProfile,
    *,
    docker_env: dict[str, str] | None = None,
    python_executable: str | None = None,
) -> str:
    docker_env = docker_env or {}
    assert_concrete_cluster_paths(profile)
    cache = profile.paths.cache or ""
    workspace = profile.paths.workspace or ""
    containers = profile.paths.containers or ""
    login = profile.ssh_alias
    scheduler = (profile.scheduler.type or "slurm").upper()
    remove = "true" if profile.remove_code_copy_after_job else "false"
    python_exe = python_executable if python_executable is not None else profile.python_executable
    isaacsim = docker_env.get("DOCKER_ISAACSIM_ROOT_PATH", "/isaac-sim")
    isaaclab = docker_env.get("DOCKER_ISAACLAB_PATH", "/workspace/isaaclab")
    user_home = docker_env.get("DOCKER_USER_HOME", "/root")
    return f"""###
# Generated by vector-sim from profile '{profile.name}'.
# vector-sim wrapper schema: {WRAPPER_SCHEMA_VERSION}
# Do not edit Isaac Lab docker/cluster/.env.cluster; this file is the source of truth.
###

CLUSTER_JOB_SCHEDULER={scheduler}
CLUSTER_ISAAC_SIM_CACHE_DIR={cache}
CLUSTER_ISAACLAB_DIR={workspace}
CLUSTER_LOGIN={login}
CLUSTER_SIF_PATH={containers}
REMOVE_CODE_COPY_AFTER_JOB={remove}
CLUSTER_PYTHON_EXECUTABLE={python_exe}

# In-container paths (equivalent to docker/.env.base)
DOCKER_ISAACSIM_ROOT_PATH={isaacsim}
DOCKER_ISAACLAB_PATH={isaaclab}
DOCKER_USER_HOME={user_home}
"""


def render_submit_job_slurm(
    profile: ClusterProfile,
    *,
    partition: str | None = None,
    gres: str | None = None,
    cpus: int | None = None,
    memory: str | None = None,
    time: str | None = None,
    output: str | None = None,
    job_label: str = "training",
    gui: bool = False,
) -> str:
    job = profile.default_job
    resolved_partition = partition if partition is not None else job.partition
    resolved_gres = gres if gres is not None else gres_request(job)
    resolved_cpus = cpus if cpus is not None else (job.cpus or 8)
    resolved_memory = memory if memory is not None else (job.memory or "32G")
    time_limit = slurm_time(time if time is not None else job.time)
    module_lines = ""
    if profile.apptainer.module:
        module_lines = f"module load {profile.apptainer.module}\n"
    shebang = "#!/bin/bash -l" if profile.scheduler.remote_shell == "login" else "#!/bin/bash"
    sbatch = "bash -l -c 'sbatch < job.sh'" if profile.scheduler.remote_shell == "login" else "sbatch < job.sh"
    partition_line = f"#SBATCH --partition={resolved_partition}\n" if resolved_partition else ""
    gres_line = f"#SBATCH --gres={resolved_gres}\n" if resolved_gres else ""
    output_line = f"#SBATCH --output={output}\n" if output else ""
    gui_note = ""
    if gui:
        gui_note = (
            "# vector-sim GUI startup runs inside run_singularity.sh:\n"
            "# Xvfb, Isaac GUI (no livestream), localhost x11vnc, noVNC/websockify.\n"
            "export VECTOR_SIM_GUI=1\n"
        )
    return f"""#!/usr/bin/env bash
set -e
# Generated by vector-sim from profile '{profile.name}'.
# vector-sim wrapper schema: {WRAPPER_SCHEMA_VERSION}
# Replaces Isaac Lab docker/cluster/submit_job_slurm.sh for this deployment.

SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" >/dev/null 2>&1 && pwd )"

cat <<EOT > job.sh
{shebang}

{partition_line}#SBATCH --ntasks=1
#SBATCH --cpus-per-task={resolved_cpus}
{gres_line}#SBATCH --time={time_limit}
#SBATCH --mem={resolved_memory}
{output_line}#SBATCH --job-name="{job_label}-$(date +"%Y-%m-%dT%H:%M")"

{module_lines}
{gui_note}bash "$SCRIPT_DIR/{RUNNER_NAME}" "$1" "$2" "${{@:3}}"
EOT

{sbatch}
rm job.sh
"""


def apptainer_exec_flag_string(profile: ClusterProfile) -> str:
    flags = [str(f) for f in profile.apptainer.extra_exec_args if str(f).strip()]
    return " ".join(flags)


def container_exec_parts(profile: ClusterProfile) -> tuple[str, str, str]:
    """Apptainer command, cache bind block, and exec flags shared with the GUI runner."""
    command = profile.apptainer.command or "singularity"
    flags = apptainer_exec_flag_string(profile)
    bind_lines = [
        f"    -B $TMPDIR/docker-isaac-sim/{rel}:{dest}:rw \\"
        for rel, dest in PERSISTENT_CACHE_BINDS
    ]
    return command, "\n".join(bind_lines), flags


def render_run_singularity(profile: ClusterProfile) -> str:
    command = profile.apptainer.command or "singularity"
    flags = apptainer_exec_flag_string(profile)
    bind_lines = []
    for rel, dest in PERSISTENT_CACHE_BINDS:
        bind_lines.append(
            f"    -B $TMPDIR/docker-isaac-sim/{rel}:{dest}:rw \\"
        )
    bind_block = "\n".join(bind_lines)
    logs_bind = "$CLUSTER_ISAACLAB_DIR/logs"
    exec_flags = flags if flags else ""
    flags_line = f"    {exec_flags} $TMPDIR/$2.sif \\" if exec_flags else "    $TMPDIR/$2.sif \\"
    return f"""#!/usr/bin/env bash
set -e
# Generated by vector-sim from profile '{profile.name}'.
# vector-sim wrapper schema: {WRAPPER_SCHEMA_VERSION}
# Replaces Isaac Lab docker/cluster/run_singularity.sh for this deployment.

echo "(run_singularity.sh): Called on compute node from current isaaclab directory $1 with container profile $2 and arguments ${{@:3}}"

setup_directories() {{
    for dir in \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/cache/kit" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/cache/ov" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/cache/pip" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/cache/glcache" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/cache/computecache" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/logs" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/data" \\
        "${{CLUSTER_ISAAC_SIM_CACHE_DIR}}/documents"; do
        if [ ! -d "$dir" ]; then
            mkdir -p "$dir"
            echo "Created directory: $dir"
        fi
    done
}}

SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_DIR/{ENV_NAME}"

setup_directories
cp -r $CLUSTER_ISAAC_SIM_CACHE_DIR $TMPDIR

mkdir -p "$CLUSTER_ISAACLAB_DIR/logs"
touch "$CLUSTER_ISAACLAB_DIR/logs/.keep"

cp -r $1 $TMPDIR
dir_name=$(basename "$1")

tar -xf $CLUSTER_SIF_PATH/$2.tar -C $TMPDIR

{command} exec \\
{bind_block}
    -B $TMPDIR/$dir_name:/workspace/isaaclab:rw \\
    -B {logs_bind}:/workspace/isaaclab/logs:rw \\
{flags_line}
    bash -c "export ISAACLAB_PATH=/workspace/isaaclab && cd /workspace/isaaclab && /isaac-sim/python.sh ${{CLUSTER_PYTHON_EXECUTABLE}} ${{@:3}}"

rsync -azPv $TMPDIR/docker-isaac-sim $CLUSTER_ISAAC_SIM_CACHE_DIR/..

if $REMOVE_CODE_COPY_AFTER_JOB; then
    rm -rf $1
fi

echo "(run_singularity.sh): Return"
"""


def generate_runtime(
    profile: ClusterProfile,
    *,
    docker_env: dict[str, str] | None = None,
    partition: str | None = None,
    gres: str | None = None,
    cpus: int | None = None,
    memory: str | None = None,
    time: str | None = None,
    output: str | None = None,
    gui: bool = False,
    python_executable: str | None = None,
    resolution: str | None = None,
) -> GeneratedRuntime:
    # Imported here so headless wrapper generation does not need the GUI renderer at import time.
    from vector_sim.jobs.gui import GUI_PYTHON, GuiLaunch, render_gui_bootstrap_script, render_gui_runner_script

    exe = python_executable
    if gui and exe is None:
        exe = GUI_PYTHON
    runner = render_run_singularity(profile)
    bootstrap = None
    if gui:
        command, bind_block, exec_flags = container_exec_parts(profile)
        launch = GuiLaunch(resolution=resolution) if resolution else GuiLaunch()
        runner = render_gui_runner_script(
            command=command,
            bind_block=bind_block,
            exec_flags=exec_flags,
            launch=launch,
        )
        bootstrap = render_gui_bootstrap_script(profile.paths.cache or "")
    return GeneratedRuntime(
        env_cluster=render_env_cluster(
            profile,
            docker_env=docker_env,
            python_executable=exe if gui else python_executable,
        ),
        submit_job_slurm=render_submit_job_slurm(
            profile,
            partition=partition,
            gres=gres,
            cpus=cpus,
            memory=memory,
            time=time,
            output=output,
            job_label="gui" if gui else "training",
            gui=gui,
        ),
        run_singularity=runner,
        gui_bootstrap=bootstrap,
    )


def write_runtime(generated: GeneratedRuntime, directory: Path) -> dict[str, Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, content in generated.as_dict().items():
        path = directory / name
        path.write_text(content)
        if name.endswith(".sh"):
            path.chmod(path.stat().st_mode | 0o111)
        written[name] = path
    return written


def load_docker_env_base(isaaclab_path: str | Path | None) -> dict[str, str]:
    values = {
        "DOCKER_ISAACSIM_ROOT_PATH": "/isaac-sim",
        "DOCKER_ISAACLAB_PATH": "/workspace/isaaclab",
        "DOCKER_USER_HOME": "/root",
    }
    if not isaaclab_path:
        return values
    env_file = Path(isaaclab_path) / "docker" / ".env.base"
    if not env_file.is_file():
        return values
    for line in env_file.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, raw = stripped.split("=", 1)
        if key in values:
            values[key] = raw.strip()
    return values
